version: "3"
services:
  app:
    build: ./
    container_name: dev-radar-backend
    command: npm run dev
    ports:
      - "8080:8080"
    volumes:
      - ./src:/server/src:z
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
